Update Battery design
UCR-Solar-Car/DriverInterface pull request #148
Opened 2022-08-25 21:38 UTC by Jyro88

Changed the ugly slime color and added horizontal lines to make sections. My original design was cooler but got replaced bc the code was "too complex". I'm salty.

2022-09-03 01:43 UTC, shahdivyank commented
Make sure to add logic so that the lines show up white explicitly

2022-09-03 20:22 UTC, IseanB requested changes
In battery.cpp, create a variable that stores battery->width(), battery->x(), battery->height() and the other values that are dereferenced multiple times. This will help reduce a lot of repetitive computations.

2022-09-03 22:04 UTC, IseanB approved these changes

2022-09-04 04:44 UTC, shahdivyank approved these changes

2022-09-04 04:44 UTC, merged